### ISSUE TITLE
 Uncaught Error: Call to undefined function GuzzleHttp\Psr7\build_query()

### ISSUE THREAD

**Issue by compadvance** [michabbb/sdk-ebay-rest-taxonomy#1]
Hi , 
Any ideas how can I can resolve that ?  php 7.4 , guzzle v 7.* installed
script is crushing on  $result = $apiInstance->fetchItemAspects($categoryTreeId); with error 
Uncaught Error: Call to undefined function GuzzleHttp\Psr7\build_query()
I tried already to rewrite obsolete function  build_query() with query::build but no luck 
Which Guzzle Version shall I use to make it working , 
Thanks in advance for any suggestions

**Comment by michabbb** [comment]
pardon, i must have missed the notification for your issue, sorry !
i re-generated the code with the latest framework and ebays latest open-api-yml file.
and I can confirm, it´s working now with PHP 8:

https://github.com/michabbb/sdk-ebay-rest-taxonomy/releases/tag/v2.0
